### ISSUE TITLE
Hang on long task

### ISSUE THREAD

**Issue by sunya-ch** [sustainable-computing-io/kepler-model-training-playbook#2]
I got a hang during some long task such as `Install package` and `Run Tekton Pipeline with S3Push` on instace_collect_role.
Anyone has an idea to fix this, please feel free to push the PR.

My current short-term solution is to rerun with changing create_instance vars to use existing spot instance requests instead of creating the new one.

```yaml
    hosts: local
    tasks:
    - include_role:
        name: create_instance
      loop:
      - { instance_type: i3en.metal, request_id: sir-xxx }
      - { instance_type: i3.metal, request_id: sir-yyy }
      vars:
        instance_type: "{{ item.instance_type }}"
        set_request_id: "{{ item.request_id }}"
```
